#!/usr/bin/env bash
# =============================================================================
#  Mystics Audit — Ubuntu deployment script
#  Target: /home/automystics-mysticsaudit/htdocs/mysticsaudit.automystics.tech
#
#  Usage on server:
#    chmod +x deploy.sh
#    ./deploy.sh              # full deploy (pull + install + build + restart)
#    ./deploy.sh --setup-db   # create postgres DB + user (run once on new server)
#    ./deploy.sh --build-only # skip git pull (re-build only)
#    ./deploy.sh --restart    # skip build, just restart PM2
# =============================================================================

set -euo pipefail

# ── Config ────────────────────────────────────────────────────────────────────
DEPLOY_DIR="/home/automystics-mysticsaudit/htdocs/mysticsaudit.automystics.tech"
REPO_URL="https://github.com/automystics-pvt-ltd/Mystics-Audit.git"
BRANCH="main"

DB_NAME="mystics_audit"
DB_USER="mystics_user"

FRONTEND_DIST="$DEPLOY_DIR/artifacts/mystics-audit/dist/public"
ENV_FILE="$DEPLOY_DIR/.env.production"

LOG="$DEPLOY_DIR/deploy.log"

# Colours
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${GREEN}[deploy]${NC} $*" | tee -a "$LOG"; }
warn()  { echo -e "${YELLOW}[warn]${NC}  $*" | tee -a "$LOG"; }
error() { echo -e "${RED}[error]${NC} $*" | tee -a "$LOG"; exit 1; }
step()  { echo -e "\n${CYAN}▶ $*${NC}" | tee -a "$LOG"; }

# ── Parse flags ───────────────────────────────────────────────────────────────
SETUP_DB=false
BUILD_ONLY=false
RESTART_ONLY=false
for arg in "$@"; do
  [[ "$arg" == "--setup-db"   ]] && SETUP_DB=true
  [[ "$arg" == "--build-only" ]] && BUILD_ONLY=true
  [[ "$arg" == "--restart"    ]] && RESTART_ONLY=true
done

mkdir -p "$DEPLOY_DIR/logs"

echo "" | tee -a "$LOG"
info "========== Deploy started at $(date) =========="

# ══════════════════════════════════════════════════════════════════════════════
#  --setup-db  : Create PostgreSQL database and user (run once on new server)
# ══════════════════════════════════════════════════════════════════════════════
if $SETUP_DB; then
  step "PostgreSQL database setup"

  # Prompt for password
  echo -e "${YELLOW}Enter a strong password for DB user '$DB_USER':${NC}"
  read -s DB_PASS
  echo ""
  [[ -z "$DB_PASS" ]] && error "Password cannot be empty."

  # Create user and database
  sudo -u postgres psql <<SQL
DO \$\$
BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '$DB_USER') THEN
    CREATE USER $DB_USER WITH PASSWORD '$DB_PASS';
    RAISE NOTICE 'User $DB_USER created.';
  ELSE
    ALTER USER $DB_USER WITH PASSWORD '$DB_PASS';
    RAISE NOTICE 'User $DB_USER password updated.';
  END IF;
END
\$\$;

SELECT 'CREATE DATABASE $DB_NAME OWNER $DB_USER'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '$DB_NAME')\gexec

GRANT ALL PRIVILEGES ON DATABASE $DB_NAME TO $DB_USER;
SQL

  info "Database '$DB_NAME' and user '$DB_USER' are ready."

  # Generate a session secret
  SESSION_SECRET_VAL=$(node -e "console.log(require('crypto').randomBytes(48).toString('hex'))")

  # Write .env.production if it doesn't already exist
  if [[ ! -f "$ENV_FILE" ]]; then
    cat > "$ENV_FILE" <<ENV
# Auto-generated by deploy.sh --setup-db on $(date)
API_PORT=8080
BASE_PATH=/
DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}
SESSION_SECRET=${SESSION_SECRET_VAL}
NODE_ENV=production

# SMTP (optional — fill in to enable email notifications)
SMTP_HOST=smtp.gmail.com
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=Mystics Audit <noreply@automystics.com>
ENV
    info ".env.production created at $ENV_FILE"
  else
    warn ".env.production already exists — skipping write. Update DATABASE_URL manually if needed."
    warn "DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@localhost:5432/${DB_NAME}"
  fi

  echo ""
  echo -e "${GREEN}✓ Database setup complete!${NC}"
  echo -e "  DB Name : $DB_NAME"
  echo -e "  DB User : $DB_USER"
  echo -e "  Env file: $ENV_FILE"
  echo ""
  echo -e "Run ${CYAN}./deploy.sh${NC} now to install, build, and start the app."
  exit 0
fi

# ══════════════════════════════════════════════════════════════════════════════
#  Normal deploy flow
# ══════════════════════════════════════════════════════════════════════════════

# ── Verify env file exists ────────────────────────────────────────────────────
[[ -f "$ENV_FILE" ]] || error ".env.production not found at $ENV_FILE\nRun: ./deploy.sh --setup-db   (to create DB + env file automatically)"
set -a; source "$ENV_FILE"; set +a
info "Environment loaded from $ENV_FILE"

# ── Check required tools ──────────────────────────────────────────────────────
for cmd in git node pnpm pm2 nginx; do
  command -v "$cmd" &>/dev/null || error "'$cmd' is not installed."
done

NODE_VER=$(node -e "process.stdout.write(process.versions.node)")
info "Node $NODE_VER · pnpm $(pnpm --version) · pm2 $(pm2 --version 2>/dev/null | head -1)"

# ── Step 1 — Clone or pull ────────────────────────────────────────────────────
if $RESTART_ONLY; then
  info "Skip: git pull (--restart mode)"
else
  step "Git — pull latest code"
  if [[ -d "$DEPLOY_DIR/.git" ]]; then
    cd "$DEPLOY_DIR"
    git fetch origin
    git reset --hard "origin/$BRANCH"
    git clean -fd
  else
    git clone --branch "$BRANCH" "$REPO_URL" "$DEPLOY_DIR"
    cd "$DEPLOY_DIR"
  fi
  info "Git: $(git log -1 --oneline)"
fi

cd "$DEPLOY_DIR"

# ── Step 2 — Install dependencies ────────────────────────────────────────────
if $RESTART_ONLY; then
  info "Skip: pnpm install (--restart mode)"
else
  step "Installing dependencies"
  pnpm install --frozen-lockfile 2>&1 | tee -a "$LOG"
fi

# ── Step 3 — Build ────────────────────────────────────────────────────────────
if $RESTART_ONLY; then
  info "Skip: build (--restart mode)"
else
  step "Building shared libraries"
  pnpm run typecheck:libs 2>&1 | tee -a "$LOG"

  step "Building API server"
  pnpm --filter @workspace/api-server run build 2>&1 | tee -a "$LOG"

  step "Building frontend (BASE_PATH=${BASE_PATH:-/})"
  PORT=3000 BASE_PATH="${BASE_PATH:-/}" \
    pnpm --filter @workspace/mystics-audit run build 2>&1 | tee -a "$LOG"

  info "Frontend output → $FRONTEND_DIST"
  ls -lh "$FRONTEND_DIST" | head -5 | tee -a "$LOG"
fi

# ── Step 4 — DB schema push ───────────────────────────────────────────────────
step "Pushing DB schema (Drizzle)"
pnpm --filter @workspace/db run push 2>&1 | tee -a "$LOG"

# ── Step 5 — Start / restart PM2 ─────────────────────────────────────────────
step "Starting services via PM2"
if pm2 list | grep -q "mystics-api"; then
  pm2 reload ecosystem.config.cjs --update-env 2>&1 | tee -a "$LOG"
else
  pm2 start ecosystem.config.cjs 2>&1 | tee -a "$LOG"
fi
pm2 save 2>&1 | tee -a "$LOG"

# ── Step 6 — Reload Nginx ─────────────────────────────────────────────────────
step "Reloading Nginx"
sudo nginx -t 2>&1 | tee -a "$LOG"
sudo systemctl reload nginx 2>&1 | tee -a "$LOG"

# ── Done ──────────────────────────────────────────────────────────────────────
info "========== Deploy finished at $(date) =========="
echo ""
echo -e "${GREEN}✓ Deployed successfully!${NC}"
echo -e "  API health → http://localhost:${API_PORT:-8080}/api/healthz"
echo -e "  Site       → https://mysticsaudit.automystics.tech"
